### ISSUE TITLE
Numpy.distutils.core

### ISSUE THREAD

**Issue by aminespinoza** [titilambert/pynuance#1]
Hi! When trying to install via pip or cloned repo I get an error.

**sudo python setup.py install**

running install
running bdist_egg
running egg_info
creating pynuance.egg-info
writing requirements to pynuance.egg-info/requires.txt
writing pynuance.egg-info/PKG-INFO
writing top-level names to pynuance.egg-info/top_level.txt
writing dependency_links to pynuance.egg-info/dependency_links.txt
writing entry points to pynuance.egg-info/entry_points.txt
writing manifest file 'pynuance.egg-info/SOURCES.txt'
package init file 'pynuance/libs/__init__.py' not found (or not a regular file)
reading manifest file 'pynuance.egg-info/SOURCES.txt'
writing manifest file 'pynuance.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pynuance
copying pynuance/websocket.py -> build/lib.linux-x86_64-2.7/pynuance
copying pynuance/tts.py -> build/lib.linux-x86_64-2.7/pynuance
copying pynuance/credentials.py -> build/lib.linux-x86_64-2.7/pynuance
copying pynuance/__main__.py -> build/lib.linux-x86_64-2.7/pynuance
copying pynuance/__init__.py -> build/lib.linux-x86_64-2.7/pynuance
copying pynuance/nlu.py -> build/lib.linux-x86_64-2.7/pynuance
copying pynuance/cli.py -> build/lib.linux-x86_64-2.7/pynuance
copying pynuance/recorder.py -> build/lib.linux-x86_64-2.7/pynuance
copying pynuance/mix.py -> build/lib.linux-x86_64-2.7/pynuance
copying pynuance/stt.py -> build/lib.linux-x86_64-2.7/pynuance
creating build/lib.linux-x86_64-2.7/pynuance/libs
copying pynuance/libs/nuance_http.py -> build/lib.linux-x86_64-2.7/pynuance/libs
copying pynuance/libs/common.py -> build/lib.linux-x86_64-2.7/pynuance/libs
copying pynuance/libs/error.py -> build/lib.linux-x86_64-2.7/pynuance/libs
copying pynuance/libs/languages.py -> build/lib.linux-x86_64-2.7/pynuance/libs
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pynuance
creating build/bdist.linux-x86_64/egg/pynuance/libs
copying build/lib.linux-x86_64-2.7/pynuance/libs/nuance_http.py -> build/bdist.linux-x86_64/egg/pynuance/libs
copying build/lib.linux-x86_64-2.7/pynuance/libs/common.py -> build/bdist.linux-x86_64/egg/pynuance/libs
copying build/lib.linux-x86_64-2.7/pynuance/libs/error.py -> build/bdist.linux-x86_64/egg/pynuance/libs
copying build/lib.linux-x86_64-2.7/pynuance/libs/languages.py -> build/bdist.linux-x86_64/egg/pynuance/libs
copying build/lib.linux-x86_64-2.7/pynuance/websocket.py -> build/bdist.linux-x86_64/egg/pynuance
copying build/lib.linux-x86_64-2.7/pynuance/tts.py -> build/bdist.linux-x86_64/egg/pynuance
copying build/lib.linux-x86_64-2.7/pynuance/credentials.py -> build/bdist.linux-x86_64/egg/pynuance
copying build/lib.linux-x86_64-2.7/pynuance/__main__.py -> build/bdist.linux-x86_64/egg/pynuance
copying build/lib.linux-x86_64-2.7/pynuance/__init__.py -> build/bdist.linux-x86_64/egg/pynuance
copying build/lib.linux-x86_64-2.7/pynuance/nlu.py -> build/bdist.linux-x86_64/egg/pynuance
copying build/lib.linux-x86_64-2.7/pynuance/cli.py -> build/bdist.linux-x86_64/egg/pynuance
copying build/lib.linux-x86_64-2.7/pynuance/recorder.py -> build/bdist.linux-x86_64/egg/pynuance
copying build/lib.linux-x86_64-2.7/pynuance/mix.py -> build/bdist.linux-x86_64/egg/pynuance
copying build/lib.linux-x86_64-2.7/pynuance/stt.py -> build/bdist.linux-x86_64/egg/pynuance
byte-compiling build/bdist.linux-x86_64/egg/pynuance/libs/nuance_http.py to nuance_http.pyc
byte-compiling build/bdist.linux-x86_64/egg/pynuance/libs/common.py to common.pyc
byte-compiling build/bdist.linux-x86_64/egg/pynuance/libs/error.py to error.pyc
byte-compiling build/bdist.linux-x86_64/egg/pynuance/libs/languages.py to languages.pyc
byte-compiling build/bdist.linux-x86_64/egg/pynuance/websocket.py to websocket.pyc
  File "build/bdist.linux-x86_64/egg/pynuance/websocket.py", line 73
    wsmsg = yield from self.stream.read()
                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/pynuance/tts.py to tts.pyc
  File "build/bdist.linux-x86_64/egg/pynuance/tts.py", line 80
    yield from client.connect(app_id, app_key)
             ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/pynuance/credentials.py to credentials.pyc
byte-compiling build/bdist.linux-x86_64/egg/pynuance/__main__.py to __main__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pynuance/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pynuance/nlu.py to nlu.pyc
  File "build/bdist.linux-x86_64/egg/pynuance/nlu.py", line 57
    yield from client.connect(app_id, app_key)
             ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/pynuance/cli.py to cli.pyc
byte-compiling build/bdist.linux-x86_64/egg/pynuance/recorder.py to recorder.pyc
  File "build/bdist.linux-x86_64/egg/pynuance/recorder.py", line 67
    yield from asyncio.wait((audiotask, receivetask),
             ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/pynuance/mix.py to mix.pyc
byte-compiling build/bdist.linux-x86_64/egg/pynuance/stt.py to stt.pyc
  File "build/bdist.linux-x86_64/egg/pynuance/stt.py", line 16
    yield from client.connect(app_id, app_key)
             ^
SyntaxError: invalid syntax

creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pynuance.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pynuance.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pynuance.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pynuance.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pynuance.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pynuance.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/pynuance-0.1.4-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pynuance-0.1.4-py2.7.egg
Copying pynuance-0.1.4-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding pynuance 0.1.4 to easy-install.pth file
Installing pynuance script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/pynuance-0.1.4-py2.7.egg
Processing dependencies for pynuance==0.1.4
Searching for speex==0.9.1
Reading https://pypi.python.org/simple/speex/
Best match: speex 0.9.1
Downloading https://pypi.python.org/packages/90/85/c4c50624de42a36965716369de69b7a5201b91331e91c3629a9301e5f156/speex-0.9.1.tar.gz#md5=40241de8a4de35546f1d63c065402e1b
Processing speex-0.9.1.tar.gz
Writing /tmp/easy_install-KUkTXb/speex-0.9.1/setup.cfg
Running speex-0.9.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-KUkTXb/speex-0.9.1/egg-dist-tmp-0n5yTb
zip_safe flag not set; analyzing archive contents...
Moving speex-0.9.1-py2.7-linux-x86_64.egg to /usr/local/lib/python2.7/dist-packages
Adding speex 0.9.1 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/speex-0.9.1-py2.7-linux-x86_64.egg
Searching for beautifulsoup4==4.6.0
Reading https://pypi.python.org/simple/beautifulsoup4/
Best match: beautifulsoup4 4.6.0
Downloading https://pypi.python.org/packages/fa/8d/1d14391fdaed5abada4e0f63543fef49b8331a34ca60c88bd521bcf7f782/beautifulsoup4-4.6.0.tar.gz#md5=c17714d0f91a23b708a592cb3c697728
Processing beautifulsoup4-4.6.0.tar.gz
Writing /tmp/easy_install-YSesRT/beautifulsoup4-4.6.0/setup.cfg
Running beautifulsoup4-4.6.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-YSesRT/beautifulsoup4-4.6.0/egg-dist-tmp-Rew27L
zip_safe flag not set; analyzing archive contents...
Moving beautifulsoup4-4.6.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding beautifulsoup4 4.6.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/beautifulsoup4-4.6.0-py2.7.egg
Searching for requests>=1.2.0
Reading https://pypi.python.org/simple/requests/
Best match: requests 2.18.4
Downloading https://pypi.python.org/packages/b0/e1/eab4fc3752e3d240468a8c0b284607899d2fbfb236a56b7377a329aa8d09/requests-2.18.4.tar.gz#md5=081412b2ef79bdc48229891af13f4d82
Processing requests-2.18.4.tar.gz
Writing /tmp/easy_install-03mP4C/requests-2.18.4/setup.cfg
Running requests-2.18.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-03mP4C/requests-2.18.4/egg-dist-tmp-wS_aNd
warning: no files found matching 'NOTICE'
creating /usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg
Extracting requests-2.18.4-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding requests 2.18.4 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg
Searching for scikits.samplerate==0.3.3
Reading https://pypi.python.org/simple/scikits.samplerate/
Best match: scikits.samplerate 0.3.3
Downloading https://pypi.python.org/packages/8f/42/532aa18dc4771190c5b7825e99c13b63ff1021e25421075756f61696e74a/scikits.samplerate-0.3.3.tar.gz#md5=96c8d8ba3aa95a9db15994f78792efb4
Processing scikits.samplerate-0.3.3.tar.gz
Writing /tmp/easy_install-pWKisq/scikits.samplerate-0.3.3/setup.cfg
Running scikits.samplerate-0.3.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-pWKisq/scikits.samplerate-0.3.3/egg-dist-tmp-lZntcl
Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    'Programming Language :: Python :: 3.5',
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 414, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 644, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 695, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 740, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1087, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 246, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-pWKisq/scikits.samplerate-0.3.3/setup.py", line 21, in <module>
    },
ImportError: No module named numpy.distutils.core

**Comment by titilambert** [comment]
You have to use python >= 3.4  and not python 2.7 (it's NOT supported)
